Phonix.Web/Models/Sample.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Phonix.Web.Models
{
    public class Sample
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string  ImagePath { get; set; }
    }
}

Phonix.Web/Controllers/SampleController.cs
using Phonix.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phonix.Web.Controllers
{
    public class SampleController : Controller
    {
        List<Sample> samples = new List<Sample>();
        private IEnumerable<Sample> AddData()
        {
            for (int i = 0; i < 10; i++)
            {
                var sample = new Sample
                {
                    Id = 1 + i,
                    Name = "Johnson"+ i.ToString(),
                    City = "New York" + i.ToString(),
                    Country = "USA" + i.ToString()
                };
                samples.Add(sample);
            }
            return samples;
        }
        // GET: Sample
        public ActionResult Index()
        {
            var samples = AddData();
            return View(samples);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sample sample)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files != null && Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Request.Files[0].FileName);
                    var filePathOfWebsite = "~/Images/Phones" + fileName;
                    Request.Files[0].SaveAs(Server.MapPath(filePathOfWebsite));
                    sample.ImagePath = filePathOfWebsite;
                }
                samples.Add(sample);
                return RedirectToAction("Index");
            }
            return View(sample);
        }
    }
}

Phonix.Web/Views/Sample/Create.cshtml
@model Phonix.Web.Models.Sample

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Sample", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sample</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Upload Image")
            <div class="col-md-10">
                <input type="file" class="form-control" name="imagePath" />
            </div>
        </div>
        @Html.HiddenFor(model => model.ImagePath);

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Phonix.Web/Views/Sample/Index.cshtml
@model IEnumerable<Phonix.Web.Models.Sample>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>