Phonix.Web/Areas/Phones/Controllers/PhoneController.cs
using AutoMapper;
using Phonix.BLL.DTO;
using Phonix.BLL.Interfaces;
using Phonix.Web.Areas.Phones.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Phonix.Web.Areas.Phones.Controllers
{
    public class PhoneController : Controller
    {
        private readonly IUserService _users;
        private readonly IPhoneService _phones;
        public PhoneController(IPhoneService phones, IUserService users)
        {
            _phones = phones;
            _users = users;
        }
        // GET: Phones/Phone
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> PhonesList()
        {
            var phones = await _phones.GetPhones();
            var phonesToReturn = new List<PhoneViewModel>();
            foreach(var p in phones)
            {
                var phone = new PhoneViewModel
                {
                    Id = p.Id,
                    Model = p.Model,
                    CompanyName = p.CompanyName,
                    ReleaseDate = p.ReleaseDate.ToShortDateString()
                };
                phonesToReturn.Add(phone);
            }
            return Json(phonesToReturn, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetPhone(int id)
        {
            var phone = await _phones.GetPhoneById(id);
            var p = new PhoneViewModel
            {
                Id = phone.Id,
                Model = phone.Model,
                CompanyName = phone.CompanyName,
                ReleaseDate = phone.ReleaseDate.ToShortDateString()
            };
            return Json(p, JsonRequestBehavior.AllowGet);
        }
        

        public async Task<JsonResult> AddPhone(PhoneViewModel phone)
        {
            if (ModelState.IsValid)
            {
                var p = new PhoneDTO
                {
                    Model = phone.Model,
                    CompanyName = phone.CompanyName,
                    ReleaseDate = Convert.ToDateTime(phone.ReleaseDate)
                };
                var result = await _phones.Add(p);
                if (result.Succeeded)
                {
                    return Json(result.Message, JsonRequestBehavior.AllowGet);
                }
                ModelState.AddModelError(result.Property, result.Message);
            }
            return Json("Error", JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> EditPhone(PhoneViewModel phone)
        {
            var p = new PhoneDTO
            {
                Id = phone.Id,
                Model = phone.Model,
                CompanyName = phone.CompanyName,
                ReleaseDate = Convert.ToDateTime(phone.ReleaseDate)
            };
            var result = await _phones.Update(p);
            return Json(result.Message, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> DeletePhone(int id)
        {
            var result = await _phones.Delete(id);
            return Json(result.Message, JsonRequestBehavior.AllowGet);
        }
    }
}

Phonix.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Phones", "Index", "Phone", new { area = "Phones" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "Users", new { area = "Admin" }, null)</li>
                        <li>@Html.ActionLink("Roles", "Index", "Roles", new { area = "Admin" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>